import{a as w,S as P,i as h}from"./assets/vendor-BPs2jpei.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const S="https://pixabay.com/api/",b="45237784-d0fd30a4ec7a7095f46d82183",x=15;let l=1,p="";async function q(r){r!==p&&(p=r,l=1);try{const e=await w.get(S,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:x,page:l}});return l+=1,e.data}catch(e){throw new Error(e.response?e.response.status:e.message)}}const $=new P(".gallery-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function m(r){h.error({position:"topRight",message:r})}function E(r){const e=r.map(({webformatURL:a,largeImageURL:i,tags:t,likes:s,views:o,comments:L,downloads:v})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${i}">
            <img class="gallery-image"
                src="${a}"
                alt="${t}" 
            />
        </a>
        <div class="gallery-content">
            <p class="text-title">Likes<span  class="text">${s}</span></p>
            <p class="text-title">Views<span  class="text">${o}</span></p>
            <p class="text-title">Comments<span  class="text">${L}</span></p>
            <p class="text-title">Downloads<span class="text">${v}</span></p>
        </div>
    </li>`).join("");document.querySelector(".gallery-list").insertAdjacentHTML("beforeend",e),$.refresh()}function I(){const r=document.querySelector(".gallery-list");r.innerHTML=""}const O=document.querySelector("#searchForm");document.querySelector(".gallery-list");const d=document.querySelector("#searchInput"),y=document.querySelector(".loading"),c=document.querySelector(".btn"),u=15;let g="",n=1;O.addEventListener("submit",async r=>{r.preventDefault(),g=d.value.trim(),n=1,I(),c.classList.add("hidden"),await f(),d.value=""});c.addEventListener("click",async()=>{await f()});async function f(){if(d.value.trim().toLowerCase()){y.classList.remove("hidden");try{const e=await q(g,n,u);if(e.hits.length===0)m("Sorry, there are no images matching your search query. Please try again!");else{if(E(e.hits),n+=1,n>1){const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}e.hits.length<u||e.totalHits<=n*u?(c.classList.add("hidden"),h.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):c.classList.remove("hidden")}}catch(e){m(e.message)}finally{y.classList.add("hidden")}}}
//# sourceMappingURL=commonHelpers.js.map
